gui:
  expandFocusedSidePanel: true
  theme:
    selectedLineBgColor:
      - reverse
  nerdFontsVersion: "3"
git:
  pagers:
    - pager: delta --dark --paging=never
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  skipHookPrefix: 'wip: '
  overrideGpg: true # prevents lazygit from spawning a separate process when using GPG
  parseEmoji: true # for use with https://gitmoji.dev
os:
  edit: cursor --reuse-window -- {{filename}}
  editAtLine: cursor --reuse-window --goto -- {{filename}}:{{line}}
  openDirInEditor: cursor -- {{dir}}
keybinding:
  universal:
    undo: '<c-u>'
    redo: '<c-z>'
